# Generated by Django 3.1.4 on 2021-02-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20), ('21', 21), ('22', 22), ('23', 23), ('24', 24), ('25', 25), ('26', 26), ('27', 27), ('28', 28), ('29', 29), ('30', 30), ('31', 31), ('32', 32), ('33', 33), ('34', 34), ('35', 35), ('36', 36), ('37', 37), ('38', 38), ('39', 39), ('40', 40), ('41', 41), ('42', 42), ('43', 43), ('44', 44), ('45', 45), ('46', 46), ('47', 47), ('48', 48), ('49', 49), ('50', 50), ('51', 51), ('52', 52), ('53', 53), ('54', 54), ('55', 55), ('56', 56), ('57', 57), ('58', 58), ('59', 59), ('60', 60), ('61', 61), ('62', 62), ('63', 63), ('64', 64), ('65', 65), ('66', 66), ('67', 67), ('68', 68), ('69', 69)], max_length=6)),
                ('caste', models.CharField(choices=[('Shah', 'Shah'), ('Arain', 'Arain')], max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('height', models.CharField(choices=[('3.0', 3.0), ('3.1', 3.1), ('3.2', 3.2), ('3.3', 3.3), ('3.4', 3.4), ('3.5', 3.5), ('3.6', 3.6), ('3.7', 3.7), ('3.8', 3.8), ('3.9', 3.9), ('4.0', 4.0), ('4.1', 4.1), ('4.2', 4.2), ('4.3', 4.3), ('4.4', 4.4), ('4.5', 4.5), ('4.6', 4.6), ('4.7', 4.7), ('4.8', 4.8), ('4.9', 4.9), ('5.0', 5.0), ('5.1', 5.1), ('5.2', 5.2), ('5.3', 5.3), ('5.4', 5.4), ('5.5', 5.5), ('5.6', 5.6), ('5.7', 5.7), ('5.8', 5.8), ('5.9', 5.9), ('6.0', 6.0), ('6.1', 6.1), ('6.2', 6.2), ('6.3', 6.3), ('6.4', 6.4), ('6.5', 6.5), ('6.6', 6.6), ('6.7', 6.7), ('6.8', 6.8), ('6.9', 6.9), ('7.0', 7.0), ('7.1', 7.1), ('7.2', 7.2), ('7.3', 7.3), ('7.4', 7.4), ('7.5', 7.5), ('7.6', 7.6), ('7.7', 7.7), ('7.8', 7.8), ('7.9', 7.9)], max_length=100)),
                ('profession', models.CharField(choices=[('Shah', 'Shah'), ('Arain', 'Arain')], max_length=100)),
                ('gardian_profession', models.CharField(choices=[('Shah', 'Shah'), ('Arain', 'Arain')], max_length=100)),
                ('siblings', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11)], max_length=6)),
                ('married_brothers', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11)], max_length=6)),
                ('married_sisters', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11)], max_length=6)),
                ('marrage_times', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('More', 'More')], max_length=10)),
                ('referance', models.CharField(max_length=30)),
                ('referance_person_detail', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.country')),
            ],
        ),
    ]
