# Generated by Django 3.1.4 on 2021-02-11 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0002_marage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marage',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marage',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
