# Generated by Django 3.1.4 on 2021-02-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Marage',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
