# Generated by Django 3.1.4 on 2021-02-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_marage_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='marage',
            name='is_approved',
            field=models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], max_length=6, null=True),
        ),
    ]
