# Generated by Django 3.1.4 on 2021-02-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_marage_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='marage',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
