# Generated by Django 3.1.4 on 2021-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_marage_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='marage',
            name='anything_else',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marage',
            name='cnic_back_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='marage',
            name='cnic_front_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='marage',
            name='facebook_id_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marage',
            name='house_bill_address_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
