# Generated by Django 3.1.7 on 2021-02-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_auto_20210301_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
